(venv) C:\Users\APC\PycharmProjects\laba_class>pytest -v issue-2.py
========================================================================================================== test session starts ===========================================================================================================
platform win32 -- Python 3.8.6, pytest-6.2.3, py-1.10.0, pluggy-0.13.1 -- c:\users\apc\pycharmprojects\laba_class\venv\scripts\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\APC\PycharmProjects\laba_class
collected 5 items                                                                                                                                                                                                                         

issue-2.py::test_1 FAILED                                                                                                                                                                                                           [ 20%]
issue-2.py::test_2 PASSED                                                                                                                                                                                                           [ 40%]
issue-2.py::test_3 PASSED                                                                                                                                                                                                           [ 60%]
issue-2.py::test_4 PASSED                                                                                                                                                                                                           [ 80%]
issue-2.py::test_5 FAILED                                                                                                                                                                                                           [100%]

================================================================================================================ FAILURES ================================================================================================================
_________________________________________________________________________________________________________________ test_1 _________________________________________________________________________________________________________________

    def test_1():
>       assert Advert({"title": "Iphone", "price": 100}) == 'Iphone | 100 ₽'
E       AssertionError: assert Iphone | 100 ₽ == 'Iphone | 100 ₽'
E         +Iphone | 100 ₽
E         -'Iphone | 100 ₽'

issue-2.py:58: AssertionError
_________________________________________________________________________________________________________________ test_5 _________________________________________________________________________________________________________________

    def test_5():
>       assert Advert({}) == "SystemExit: 1"

issue-2.py:81:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
issue-2.py:42: in __init__
    exit(1)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = Use exit() or Ctrl-Z plus Return to exit, code = 1

    def __call__(self, code=None):
        # Shells like IDLE catch the SystemExit, but listen when their
        # stdin wrapper is closed.
        try:
            sys.stdin.close()
        except:
            pass
>       raise SystemExit(code)
E       SystemExit: 1

C:\Program Files (x86)\Python38-32\lib\_sitebuiltins.py:26: SystemExit
---------------------------------------------------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------------------------------------------------
Отсутствует поле title
======================================================================================================== short test summary info =========================================================================================================
FAILED issue-2.py::test_1 - AssertionError: assert Iphone | 100 ₽ == 'Iphone | 100 ₽'
FAILED issue-2.py::test_5 - SystemExit: 1
====================================================================================================== 2 failed, 3 passed in 0.13s =======================================================================================================

